### ISSUE TITLE
M2T Performance Related

### ISSUE THREAD

**Issue by LeeYufang** [viatra/viatra-cps-benchmark#13]
Hi, 
I run M2T performance test using your cps benchmark, with the following program arguments and VM arguments.
Program Arguments:
-transformationType:        INCR_VIATRA_EXPLICIT_TRACEABILITY
-scale:       16/32/64/128
-generatorType:      TEMPLATE/JDT 
-runIndex:    1 
-case:      LOW_SYNCH  
-scenario:    TOOLCHAIN_INCREMENTAL
VM Arguments:
-Xms32G   -Xmx64G
And my computer is Linux Redhat, 256 RAM, Core E5-2670 CPU. 
The tables below are the time values of M2TTransformation2 (the iteration times is 5)

                                             Table1   TEMLATE

| scale	 |   1st M2T2	|   2nd M2T2	|   3rd M2T2	|     4th M2T2	 | 5th M2T2 
| ------- | ----------- | ------------- | ------------ | ------------- | -------- 
| 16     |   14313394   |    30534771   |     38629383  |     50393830 |    62164960
| 32     |   305587850  |   25380039    |    37398958   |     50269827 |   69724793
| 64     |   1081044253 |   25258486    |   45648783    |     50439923  |  61270429
| 128    |   1342069855 |   26053416    |  37065752     |     54832896   | 62607682

                                            Table2  JDT
| scale	 |   1st M2T2	  | 2nd M2T2	|    3rd M2T2	  |    4th M2T2	 | 5th M2T2
| ------- | ----------- | ------------- | ------------ | ------------- | -------- 
| 16     |    14711613    |   30813995  |      40254683   |    55677344  |   68517079
| 32     |    325140007   |  30202822   |     39284459    |     63334132 |    67216697
| 64     |    1046913870  |  27889867   |     40281488    |    56218919  |   64280250
| 128    |   7584430918   |  28930511   |     46184705    |     52141219 |    64611885

When the scale is 32,64, 128 and the generatorType is TEMPLATE, the time value of the first M2TTransformation2 is much bigger than that of these latter four ones in Table1.
And the same in Table2, when the scale is 32,64, 128 and the generatorType is JDT, the time value of the first M2TTransformation2 is much bigger than that of these latter four ones in Table2.

(1). So I am a litter confused,  do I miss something or set the wrong configurations? Or it is the normal 
      situation?
(2). Is it convient for you to give me more materials of M2T or your M2T performance test results?
  Sorry to disturb you, hope for your reply.

**Comment by abelhegedus** [comment]
First, I have edited your comment to make the tables more readable.

We have not done in-depth benchmarking on M2T transformations, so I cannot say whether the values are close to what we expect, but I can share some details on why this could be.

* If I understand correctly, you are running the benchmark as an Eclipse application. What is contained in a workspace that this application uses? Do you delete the complete workspace every time you execute the transformation?
* The M2T2 phase for the incremental scenario uses the [M2TDeltaTransformationPhase](https://github.com/viatra/viatra-cps-benchmark/blob/master/tests/com.incquerylabs.examples.cps.performance.tests/src/com/incquerylabs/examples/cps/performance/tests/config/phases/M2TDeltaTransformationPhase.xtend), and I just noticed that it does not create a checkpoint in the monitor, so it always runs on all changes after the initial run. Though this would increase the runtime, not decrease it. This can be observed by the fact that the later runtimes increase consistently.
* You can see that for Eclipse applications, the generated files are put into the workspace, and we noticed that sometimes the amount of content in the same workspace can take a lot of time to process once. However, the initial M2T1 phase should have triggered anything like that earlier.
* The transformation does have to delete and create a lot of files, but that usually only trips up Windows, not Linux. Also, at least the same amount of work is done by the later iterations as well, so that doesn't explain things.
* The other issue that may occur is if the first execution somehow runs on all the model instead of only on the changed parts. But then the rest of the iterations would also do that, since the checkpoint creation is buggy.

So, in all, without knowing how much time the various parts of the phase take in the first iteration or the contents of the change monitor, I cannot tell you what happens. I agree that the results are not as expected, I will execute some tests to see if I can reproduce the same results.

**Comment by LeeYufang** [comment]
Hi, abelhegedus
Thanks your kind explaination.  And here are my answers to your questions.
(1) If I understand correctly, you are running the benchmark as an Eclipse application. 
     Yes, you are right, I run the benchmark as an Eclipse application.
(2) What is contained in a workspace that this application uses?
     I downlod the "org.eclipse.viatra.examples-master.zip" and "viatra-cps-benchmark-master.zip" from "https://github.com/viatra/org.eclipse.viatra.examples" and "https://github.com/viatra/viatra-cps-benchmark". And then import all projects of org.eclipse.viatra.examples-master and all cps projects of org.eclipse.viatra.examples-master into my workspace.
(3). Do you delete the complete workspace every time you execute the transformation?
      I just delete the results file and the runtime-app_headless.product file every time before next run.

So, if you have results or conclusions of M2T test, would you please get touch with me?
Sorry to disturb you and thanks very much.

**Comment by LeeYufang** [comment]
Hi, abelhegedus
Thanks for your kind explaination. And here are my answers to your questions.
 (1) If I understand correctly, you are running the benchmark as an Eclipse application.
     Yes, you are right, I run the benchmark as an Eclipse application.
 (2) What is contained in a workspace that this application uses?
      I downlod the "org.eclipse.viatra.examples-master.zip" and "viatra-cps-benchmark-master.zip" 
      from "https://github.com/viatra/org.eclipse.viatra.examples" and "https://github.com/viatra/viatra-
      cps-benchmark". And then import all projects of org.eclipse.viatra.examples-master and all cps 
      projects of org.eclipse.viatra.examples-master into my workspace.
 (3) Do you delete the complete workspace every time you execute the transformation?
      I just delete the results file and the runtime-app_headless.product file every time before next run.

So, if you have results or conclusions of M2T test, would you please get touch with me?
Sorry to disturb you and thanks very much.

**Comment by abelhegedus** [comment]
> (2) What is contained in a workspace that this application uses?
I downlod the "org.eclipse.viatra.examples-master.zip" and "viatra-cps-benchmark-master.zip"
from "https://github.com/viatra/org.eclipse.viatra.examples" and "https://github.com/viatra/viatra-
cps-benchmark". And then import all projects of org.eclipse.viatra.examples-master and all cps
projects of org.eclipse.viatra.examples-master into my workspace.

I mean the workspace that the benchmark Eclipse Application uses (see Run... -> Run Configurations and on the Main tab, under "Workspace Data Location").
Please check that you have nothing important in the directory given there and check "Clear [x] workspace" to make sure that it is always empty when starting the benchmark.

>(3) Do you delete the complete workspace every time you execute the transformation?
I just delete the results file and the runtime-app_headless.product file every time before next run

Again, my question was related to the benchmark application workspace, not the host workspace.

> So, if you have results or conclusions of M2T test, would you please get touch with me?

I have fixed the bug in the M2TDeltaTransformationPhase (see fe3a8582c68b2e5ac66f336404b0abd3fabf8ba4 ) and will perform some tests as well. I'll get back to you with the results.

**Comment by abelhegedus** [comment]
Just a short update: the issue occurs on my machine as well, I will take a closer look at what is different in the first iteration.

From what I can see, the first time the fileAccessor is used the createFile method takes two orders of magnitude more than later calls.

**Comment by LeeYufang** [comment]
Morning,
I hava checked my benchmark Eclipse Application Configuration(Run... -> Run Configurations and on the Main tab, under "Workspace Data Location), "Location" of "Workspace Data" is "${workspace_loc}/../runtime-app_headless.product"  and "workspace" is selected in the "clear" item.

Have a nice day and hope for your next contact.

**Comment by abelhegedus** [comment]
I found that the workspace delta processing from the initial M2T phase was still running at the time of the M2TDelta phase and it blocked further file modifications.

In c39c453cf97ce35f3586ca4c305829b8dbe6e053 I have wrapped serialization in a single workspace operation, which seems to have solved the issue for me.

**Comment by LeeYufang** [comment]
Hi,
I hava run cps benchmark m2t using the lastest codes you uploaded with the configurations which was mentioned in my first comment. It seems that one result of scale 128 and 256 of M2T2 is bigger than the other four ones, as the iteration time is 5. 

                                               TEMPLATE

scale    |    M2T2-1       |    M2T2-2      |    M2T2-3    |    M2T2-4       |   M2T2-5
 ------- | ----------- | ------------- | ------------ | ------------- | -------- 
128     |  14,575,317    |  13,934,471   |  13,553,207  |   22,361,241  |  109,109,167
256     |  148,890,748  |  13,760,813   |  13,468,540  |   18,495,176  |  13,726,373

                                                      JDT

scale     |     M2T2-1       |      M2T2-2     |      M2T2-3      |    M2T2-4       |    M2T2-5
 ------- | ----------- | ------------- | ------------ | ------------- | -------- 
128      |    16,530,862   |    24,326,912  |   14,188,744    |   13,847,084   |   110,420,819
256      |    145,720,976 |     14,314,839 |    19,969,840   |    29,152,980   |   14,614,330

Did you encounter this situlation? It happens for me every time.
Does it have relatation with the runnable?
Sorry to disturb you again and hope for your reply.

**Comment by abelhegedus** [comment]
Do you see the same on lower scales?

If not, my only guess would be that for some reason you run into GC stops in one out of five executions, which is strange since previous phases perform manual GC for memory measurements.
I don't think it relates to the introduction of the runnable or the change monitor bugfix, but there can be something I have overlooked.

I did a short test on my machine with -Xms4G -Xmx8G and got the following results (with JDT M2T variant):

scale     |     M2T2-1       |      M2T2-2     |      M2T2-3      |    M2T2-4       |    M2T2-5
 ------- | ----------- | ------------- | ------------ | ------------- | -------- 
32      |    25,312,989   |    23,580,067  |   31,219,584    |   32,790,592   |   31,256,780
64      |    32,029,521   |    31,179,105  |   28,026,879    |   21,980,614   |   **43,362,802**
128      |    **66,740,112**   |    **162,702,863**  |   27,333,638    |   25,273,240   |   35,032,232
256      |    25,495,690 |     25,550,755 |    24,458,563   |    **39,981,562**   |   27,426,264

As you can see in **bold**, I also got some slowdowns, but not consistently one order of magnitude larger than the rest of the values.

**Comment by LeeYufang** [comment]
Thanks for your reply.
Q: Do you see the same on lower scales?
A: In my lower scale and larger scales, there are also some slowdowns, not one order of magnitude larger than the rest of the values as the situation in scale 128 and 256 shows. In 128 and 256, the abnormal value is much bigger than the rest of the values.

Thanks and hope for your reply.
