### ISSUE TITLE
Open big files slowly with Xtext editor

### ISSUE THREAD

**Issue by LeeYufang** [viatra/viatra-cps-benchmark#19]
Hi,
  I am opening a big dsl file(about 52M) with the xtext editor, and it takes about 505s. Though it is opened, it is hardly editable because the wokbench is froozen if I click the contents in the editor. So I want to reduce the time of opening and make the file editable in the xtext editor.
Do you have some suggestions to turn off all functions that prevents to open and type on it? or some optimized methods?
Thanks in advance.

**Comment by ujhelyiz** [comment]
Hi,

I know of a lot of editors (even outside Eclipse) that have issues with editing a 52 MB text files. Yes, Xtext can be slow and in general the only true recommendation I can give is to split your files into many smaller ones. Or if you want to do some minor editing, simply open the files in question in any text editor.

Given this repository is not about Xtext-based DSLs, I am closing this issue here. If you want more specific answers, I'd recommend either going to the [Xtext forums](https://www.eclipse.org/forums/index.php/f/27/) or the [Xtext tag of Stack Overflow](https://stackoverflow.com/questions/tagged/xtext) - both places are regularly monitored by Xtext developers who might have better answer to your question.

Best regards.
